name: Feature request
about: Suggest an idea for this project
title: "[FEATURE]"
labels: enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the problem is. Ex. I am always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow with our [Code of Conduct](https://github.com/FeroxFoxxo/DiscordSlash/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow with the Code of Conduct.
          required: true
